from __future__ import annotations

import json
from contextlib import contextmanager
from dataclasses import dataclass, field, fields
from pathlib import Path
from typing import Any, Dict, Iterator, Mapping, Optional, Protocol, Union

import torch
import torch.nn as nn

from .diagnostic_model_structure import render_model_structure


class DiagnosticRegistryLike(Protocol):
    def store(
        self,
        stage: str,
        metric_name: str,
        value: Any,
        **kwargs,
    ) -> None:
        ...

    def store_many(
        self,
        stage: str,
        metrics: Dict[str, Any],
        **kwargs,
    ) -> None:
        ...


@dataclass
class StageProbeConfig:
    """Runtime probe policy for one registered model module."""

    # Master switch. JSON generated by Step 1 defaults this to False.
    enabled: bool = False

    # Forward activation diagnostics.
    activation: bool = False
    activation_every: int = 50
    capture_input_activation: bool = True
    capture_output_activation: bool = True

    # Parameter gradient diagnostics. Collected after loss.backward().
    gradient: bool = False
    gradient_every: int = 50

    # Parameter value diagnostics.
    parameter: bool = False
    parameter_every: int = 100

    # Module input/output gradient-flow diagnostics.
    backward_flow: bool = False
    backward_flow_every: int = 50

    # Actual optimizer update diagnostics. Requires parameter snapshots.
    update: bool = False
    update_every: int = 100

    @classmethod
    def from_mapping(cls, values: Mapping[str, Any]) -> "StageProbeConfig":
        """
        Build a config from the module's ``diagnostics`` JSON object.

        The six boolean fields generated by render_model_structure() are enough
        for normal use. Optional cadence/capture fields may be added later
        without changing the static-structure schema.
        """
        known = {f.name for f in fields(cls)}
        unknown = set(values) - known
        if unknown:
            raise ValueError(
                "Unknown diagnostic config field(s): " + ", ".join(sorted(unknown))
            )

        kwargs = dict(values)

        for name in (
            "enabled",
            "activation",
            "capture_input_activation",
            "capture_output_activation",
            "gradient",
            "parameter",
            "backward_flow",
            "update",
        ):
            if name in kwargs and not isinstance(kwargs[name], bool):
                raise TypeError(f"Diagnostic field '{name}' must be boolean")

        for name in (
            "activation_every",
            "gradient_every",
            "parameter_every",
            "backward_flow_every",
            "update_every",
        ):
            if name in kwargs:
                value = kwargs[name]
                if not isinstance(value, int) or value <= 0:
                    raise ValueError(f"Diagnostic field '{name}' must be a positive integer")

        return cls(**kwargs)


@dataclass
class ProbeContext:
    step: Optional[int] = None
    epoch: Optional[int] = None
    phase: str = "train"
    tags: Dict[str, Any] = field(default_factory=dict)


@dataclass
class _StageEntry:
    stage: str
    module_path: str
    module: nn.Module
    config: StageProbeConfig


class DiagnosticProbeManager:
    """
    PyTorch-aware metric collector that writes compact diagnostics into a
    DiagnosticRegistry.

    Responsibilities:
      * load the Step-1 static-structure JSON / diagnostic flags,
      * resolve enabled module paths against the current model,
      * attach activation/backward hooks when requested,
      * collect gradient/parameter/update metrics at explicit training points,
      * add training/evaluation context to records.

    It intentionally does not own metric history or AI-agent query logic; those
    remain in DiagnosticRegistry.
    """

    def __init__(
        self,
        model: nn.Module,
        registry: DiagnosticRegistryLike,
    ):
        if not isinstance(model, nn.Module):
            raise TypeError("model must be an instance of torch.nn.Module")

        self.model = model
        self.registry = registry

        self.model_structure: Optional[Dict[str, Any]] = None
        self._stages: Dict[str, _StageEntry] = {}
        self._forward_handles: Dict[str, Any] = {}
        self._backward_handles: Dict[str, Any] = {}
        self._update_snapshots: Dict[str, Dict[str, torch.Tensor]] = {}
        self._context = ProbeContext()
        self._started = False

    # ------------------------------------------------------------------
    # Static structure / JSON config integration
    # ------------------------------------------------------------------

    def render_model_structure(
        self,
        *,
        model_name: Optional[str] = None,
        output_path: Optional[Union[str, Path]] = None,
    ) -> Dict[str, Any]:
        """Render Step-1 static model structure without running forward()."""
        self.model_structure = render_model_structure(
            self.model,
            model_name=model_name,
            output_path=output_path,
        )
        return self.model_structure

    @staticmethod
    def _read_structure_source(
        source: Union[str, Path, Mapping[str, Any]],
    ) -> Dict[str, Any]:
        if isinstance(source, Mapping):
            return dict(source)

        path = Path(source)
        with path.open("r", encoding="utf-8") as f:
            payload = json.load(f)

        if not isinstance(payload, dict):
            raise ValueError("Diagnostic structure JSON must contain a JSON object")
        return payload

    def load_structure_config(
        self,
        source: Union[str, Path, Mapping[str, Any]],
        *,
        validate_structure: bool = False,
        replace_existing: bool = True,
    ) -> Dict[str, Any]:
        """Load diagnostic policy and register enabled module paths.

        ``validate_structure`` is retained only for caller compatibility and is a
        no-op. structure_id is informational; it is never used as a validation gate.
        The caller/runtime is responsible for mapping policy onto the current model.
        """
        structure = self._read_structure_source(source)
        self._validate_structure_document(structure)

        if replace_existing:
            if self._started:
                self.stop()
            self._stages.clear()

        seen_module_instances: Dict[int, str] = {}

        for module_record in structure["modules"]:
            diagnostics = module_record.get("diagnostics", {})
            cfg = StageProbeConfig.from_mapping(diagnostics)
            if not cfg.enabled:
                continue

            module_path = module_record.get("module_path")
            if not isinstance(module_path, str):
                raise ValueError("Every module record must contain a string module_path")

            try:
                module = (
                    self.model
                    if module_path == ""
                    else self.model.get_submodule(module_path)
                )
            except AttributeError as exc:
                raise ValueError(
                    f"Enabled diagnostic module path {module_path!r} does not exist "
                    "in the current model. Runtime policy mapping should remove or "
                    "remap stale paths before probe registration."
                ) from exc

            stage_name = module_path if module_path else "<root>"

            existing = seen_module_instances.get(id(module))
            if existing is not None:
                raise ValueError(
                    f"Enabled diagnostic modules '{existing}' and '{stage_name}' refer to "
                    "the same shared nn.Module instance. Enable only one alias."
                )
            seen_module_instances[id(module)] = stage_name

            self.register_stage(
                stage=stage_name,
                module=module,
                module_path=module_path,
                config=cfg,
            )

        self.model_structure = structure
        return structure

    @staticmethod
    def _validate_structure_document(structure: Mapping[str, Any]) -> None:
        if structure.get("artifact_type") != "pytorch_static_model_structure":
            raise ValueError(
                "Expected artifact_type='pytorch_static_model_structure'"
            )
        modules = structure.get("modules")
        if not isinstance(modules, list):
            raise ValueError("Diagnostic structure JSON must contain a 'modules' list")
        # structure_id is intentionally optional/informational.

    # ------------------------------------------------------------------
    # Registration / lifecycle
    # ------------------------------------------------------------------

    def register_stage(
        self,
        stage: str,
        module: Union[str, nn.Module],
        *,
        module_path: Optional[str] = None,
        config: Optional[StageProbeConfig] = None,
    ) -> None:
        if isinstance(module, str):
            module_path = module
            module_obj = self.model if module == "" else self.model.get_submodule(module)
        else:
            module_obj = module

        if not isinstance(module_obj, nn.Module):
            raise TypeError(f"Stage '{stage}' does not resolve to nn.Module")

        entry = _StageEntry(
            stage=stage,
            module_path=module_path if module_path is not None else stage,
            module=module_obj,
            config=config or StageProbeConfig(),
        )
        self._stages[stage] = entry

        if self._started:
            self._attach_stage_hooks(entry)

    def list_stages(self) -> Dict[str, Dict[str, Any]]:
        return {
            name: {
                "module_path": entry.module_path,
                "module_type": type(entry.module).__name__,
                "config": vars(entry.config).copy(),
            }
            for name, entry in self._stages.items()
        }

    def start(self) -> None:
        if self._started:
            return
        self._started = True
        for entry in self._stages.values():
            self._attach_stage_hooks(entry)

    def stop(self) -> None:
        for handle in self._forward_handles.values():
            handle.remove()
        for handle in self._backward_handles.values():
            handle.remove()

        self._forward_handles.clear()
        self._backward_handles.clear()
        self._update_snapshots.clear()
        self._started = False

    def close(self) -> None:
        self.stop()

    # ------------------------------------------------------------------
    # Step context / registry convenience
    # ------------------------------------------------------------------

    def begin_step(
        self,
        step: Optional[int],
        *,
        epoch: Optional[int] = None,
        phase: str = "train",
        tags: Optional[Dict[str, Any]] = None,
    ) -> None:
        self._context = ProbeContext(
            step=step,
            epoch=epoch,
            phase=phase,
            tags=dict(tags or {}),
        )

    @contextmanager
    def step(
        self,
        step: Optional[int],
        *,
        epoch: Optional[int] = None,
        phase: str = "train",
        tags: Optional[Dict[str, Any]] = None,
    ) -> Iterator["DiagnosticProbeManager"]:
        previous = self._context
        self.begin_step(step, epoch=epoch, phase=phase, tags=tags)
        try:
            yield self
        finally:
            self._context = previous

    def store(
        self,
        stage: str,
        metric_name: str,
        value: Any,
        *,
        tags: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.registry.store(
            stage=stage,
            metric_name=metric_name,
            value=value,
            step=self._context.step,
            epoch=self._context.epoch,
            phase=self._context.phase,
            tags=self._merge_tags(tags),
        )

    def store_many(
        self,
        stage: str,
        metrics: Dict[str, Any],
        *,
        tags: Optional[Dict[str, Any]] = None,
    ) -> None:
        self.registry.store_many(
            stage=stage,
            metrics=metrics,
            step=self._context.step,
            epoch=self._context.epoch,
            phase=self._context.phase,
            tags=self._merge_tags(tags),
        )

    # ------------------------------------------------------------------
    # Activation / backward-flow hooks
    # ------------------------------------------------------------------

    def _attach_stage_hooks(self, entry: _StageEntry) -> None:
        cfg = entry.config
        stage = entry.stage

        if not cfg.enabled:
            return

        if cfg.activation and stage not in self._forward_handles:
            self._forward_handles[stage] = entry.module.register_forward_hook(
                self._create_forward_hook(stage)
            )

        if cfg.backward_flow and stage not in self._backward_handles:
            self._backward_handles[stage] = entry.module.register_full_backward_hook(
                self._create_backward_hook(stage)
            )

    def _create_forward_hook(self, stage: str):
        def hook(module: nn.Module, inputs: Any, output: Any) -> None:
            entry = self._stages.get(stage)
            if entry is None:
                return
            cfg = entry.config
            if not self._should_collect(cfg.enabled and cfg.activation, cfg.activation_every):
                return

            metrics: Dict[str, Any] = {}

            if cfg.capture_input_activation:
                self._add_activation_metrics(metrics, "activation.input", inputs)

            if cfg.capture_output_activation:
                self._add_activation_metrics(metrics, "activation.output", output)

            if metrics:
                self.store_many(stage, metrics)

        return hook

    def _create_backward_hook(self, stage: str):
        def hook(module: nn.Module, grad_input: Any, grad_output: Any) -> None:
            entry = self._stages.get(stage)
            if entry is None:
                return
            cfg = entry.config
            if not self._should_collect(
                cfg.enabled and cfg.backward_flow,
                cfg.backward_flow_every,
            ):
                return

            metrics: Dict[str, Any] = {}
            self._add_activation_metrics(metrics, "grad.flow.input", grad_input)
            self._add_activation_metrics(metrics, "grad.flow.output", grad_output)
            if metrics:
                self.store_many(stage, metrics)

        return hook

    @classmethod
    def _add_activation_metrics(
        cls,
        target: Dict[str, Any],
        prefix: str,
        value: Any,
    ) -> None:
        tensors = list(cls._iter_tensors(value))
        if not tensors:
            return

        # Shape is intentionally collected whenever activation diagnostics are
        # enabled; it is runtime information and therefore does not belong in
        # the Step-1 static JSON.
        shapes = [list(t.shape) for t in tensors]
        target[f"{prefix}.shape"] = shapes[0] if len(shapes) == 1 else shapes

        stats = cls._aggregate_tensors(tensors)
        for name in (
            "mean",
            "std",
            "rms",
            "abs_max",
            "zero_frac",
            "nonfinite_frac",
        ):
            target[f"{prefix}.{name}"] = stats[name]

    # ------------------------------------------------------------------
    # Explicit training collection points
    # ------------------------------------------------------------------

    def after_backward(self, stage: Optional[str] = None) -> None:
        """Collect configured parameter-gradient/parameter metrics."""
        for entry in self._select_stages(stage):
            cfg = entry.config
            if not cfg.enabled:
                continue

            if self._should_collect(cfg.gradient, cfg.gradient_every):
                self.store_many(entry.stage, self._collect_gradient_stats(entry.module))

            if self._should_collect(cfg.parameter, cfg.parameter_every):
                self.store_many(entry.stage, self._collect_parameter_stats(entry.module))

    def collect_parameters(self, stage: Optional[str] = None) -> None:
        for entry in self._select_stages(stage):
            if entry.config.enabled:
                self.store_many(entry.stage, self._collect_parameter_stats(entry.module))

    def before_optimizer_step(self, stage: Optional[str] = None) -> None:
        """Snapshot only stages with update diagnostics enabled for this step."""
        for entry in self._select_stages(stage):
            cfg = entry.config
            if not cfg.enabled or not self._should_collect(cfg.update, cfg.update_every):
                continue

            self._update_snapshots[entry.stage] = {
                name: p.detach().clone()
                for name, p in entry.module.named_parameters()
                if p.requires_grad
            }

    def after_optimizer_step(self, stage: Optional[str] = None) -> None:
        for entry in self._select_stages(stage):
            snapshot = self._update_snapshots.pop(entry.stage, None)
            if not snapshot:
                continue
            self.store_many(
                entry.stage,
                self._collect_update_stats(entry.module, snapshot),
            )

    # ------------------------------------------------------------------
    # Dynamic runtime configuration
    # ------------------------------------------------------------------

    def configure_stage(self, stage: str, **kwargs: Any) -> None:
        entry = self._stages.get(stage)
        if entry is None:
            raise KeyError(f"Unknown diagnostic stage: {stage}")

        valid = {f.name for f in fields(StageProbeConfig)}
        unknown = set(kwargs) - valid
        if unknown:
            raise ValueError(
                "Unknown StageProbeConfig option(s): " + ", ".join(sorted(unknown))
            )

        hook_related = bool(set(kwargs) & {"enabled", "activation", "backward_flow"})
        for name, value in kwargs.items():
            setattr(entry.config, name, value)

        if hook_related and self._started:
            self._refresh_stage_hooks(stage)

    # ------------------------------------------------------------------
    # Metric implementations
    # ------------------------------------------------------------------

    @staticmethod
    def _collect_gradient_stats(module: nn.Module) -> Dict[str, Any]:
        grads = []
        trainable_numel = 0
        grad_numel = 0

        for p in module.parameters():
            if not p.requires_grad:
                continue
            trainable_numel += p.numel()
            if p.grad is None or p.grad.numel() == 0:
                continue
            grads.append(p.grad.detach())
            grad_numel += p.grad.numel()

        if not grads:
            return {
                "grad.param.l2": 0.0,
                "grad.param.rms": 0.0,
                "grad.param.abs_mean": 0.0,
                "grad.param.abs_max": 0.0,
                "grad.param.coverage": 0.0,
                "grad.param.nonfinite_frac": 0.0,
            }

        stats = DiagnosticProbeManager._aggregate_tensors(grads)
        return {
            "grad.param.l2": stats["l2"],
            "grad.param.rms": stats["rms"],
            "grad.param.abs_mean": stats["abs_mean"],
            "grad.param.abs_max": stats["abs_max"],
            "grad.param.coverage": (
                grad_numel / trainable_numel if trainable_numel else 0.0
            ),
            "grad.param.nonfinite_frac": stats["nonfinite_frac"],
        }

    @staticmethod
    def _collect_parameter_stats(module: nn.Module) -> Dict[str, Any]:
        params = [
            p.detach()
            for p in module.parameters()
            if p.requires_grad and p.numel() > 0
        ]
        if not params:
            return {
                "param.l2": 0.0,
                "param.rms": 0.0,
                "param.abs_mean": 0.0,
                "param.abs_max": 0.0,
                "param.nonfinite_frac": 0.0,
            }

        stats = DiagnosticProbeManager._aggregate_tensors(params)
        return {
            "param.l2": stats["l2"],
            "param.rms": stats["rms"],
            "param.abs_mean": stats["abs_mean"],
            "param.abs_max": stats["abs_max"],
            "param.nonfinite_frac": stats["nonfinite_frac"],
        }

    @staticmethod
    def _collect_update_stats(
        module: nn.Module,
        snapshot: Dict[str, torch.Tensor],
    ) -> Dict[str, Any]:
        deltas = []
        weights = []

        for name, p in module.named_parameters():
            before = snapshot.get(name)
            if before is None:
                continue
            after = p.detach()
            deltas.append(after - before)
            weights.append(after)

        if not deltas:
            return {
                "update.l2": 0.0,
                "update.rms": 0.0,
                "update.to_weight_ratio": 0.0,
            }

        update_stats = DiagnosticProbeManager._aggregate_tensors(deltas)
        weight_stats = DiagnosticProbeManager._aggregate_tensors(weights)
        weight_l2 = weight_stats["l2"]
        return {
            "update.l2": update_stats["l2"],
            "update.rms": update_stats["rms"],
            "update.to_weight_ratio": (
                update_stats["l2"] / weight_l2 if weight_l2 > 0 else 0.0
            ),
        }

    @staticmethod
    def _iter_tensors(value: Any):
        if torch.is_tensor(value):
            if value.numel() > 0:
                yield value.detach()
            return

        if isinstance(value, Mapping):
            for item in value.values():
                yield from DiagnosticProbeManager._iter_tensors(item)
            return

        if isinstance(value, (list, tuple)):
            for item in value:
                yield from DiagnosticProbeManager._iter_tensors(item)

    @staticmethod
    def _aggregate_tensors(tensors) -> Dict[str, Any]:
        """
        Aggregate compact statistics without materializing tensors on CPU.

        Reductions stay on each tensor's device; one small packed vector per
        device is copied to CPU. Non-finite values are excluded from mean/std/
        norm statistics but are counted in nonfinite_frac.
        """
        tensors = [
            t.detach()
            for t in tensors
            if torch.is_tensor(t) and t.numel() > 0
        ]
        if not tensors:
            return {
                "mean": 0.0,
                "std": 0.0,
                "rms": 0.0,
                "l2": 0.0,
                "abs_mean": 0.0,
                "abs_max": 0.0,
                "zero_frac": 0.0,
                "nonfinite_frac": 0.0,
                "numel": 0,
                "finite_numel": 0,
            }

        groups: Dict[torch.device, list[torch.Tensor]] = {}
        for tensor in tensors:
            groups.setdefault(tensor.device, []).append(tensor)

        total_numel = 0
        finite_numel = 0
        total_sum = 0.0
        total_sq = 0.0
        total_abs_sum = 0.0
        total_abs_max = 0.0
        total_zero = 0.0
        total_nonfinite = 0.0

        for device_tensors in groups.values():
            packed_sum = None

            for tensor in device_tensors:
                x = tensor.float()
                finite = torch.isfinite(x)
                safe = torch.where(finite, x, torch.zeros_like(x))

                packed = torch.stack(
                    [
                        torch.tensor(float(x.numel()), device=x.device),
                        finite.sum().float(),
                        safe.sum(),
                        (safe * safe).sum(),
                        safe.abs().sum(),
                        safe.abs().max(),
                        (finite & (x == 0)).sum().float(),
                        (~finite).sum().float(),
                    ]
                )

                if packed_sum is None:
                    packed_sum = packed
                else:
                    # Sum all fields except abs_max, which uses max.
                    packed_sum[:5] = packed_sum[:5] + packed[:5]
                    packed_sum[5] = torch.maximum(packed_sum[5], packed[5])
                    packed_sum[6:] = packed_sum[6:] + packed[6:]

            if packed_sum is None:
                continue

            values = packed_sum.detach().cpu().tolist()
            total_numel += int(values[0])
            finite_numel += int(values[1])
            total_sum += values[2]
            total_sq += values[3]
            total_abs_sum += values[4]
            total_abs_max = max(total_abs_max, values[5])
            total_zero += values[6]
            total_nonfinite += values[7]

        if total_numel == 0:
            return {
                "mean": 0.0,
                "std": 0.0,
                "rms": 0.0,
                "l2": 0.0,
                "abs_mean": 0.0,
                "abs_max": 0.0,
                "zero_frac": 0.0,
                "nonfinite_frac": 0.0,
                "numel": 0,
                "finite_numel": 0,
            }

        if finite_numel:
            mean = total_sum / finite_numel
            variance = max(total_sq / finite_numel - mean * mean, 0.0)
            std = variance ** 0.5
            rms = (total_sq / finite_numel) ** 0.5
            abs_mean = total_abs_sum / finite_numel
        else:
            mean = std = rms = abs_mean = 0.0

        return {
            "mean": mean,
            "std": std,
            "rms": rms,
            "l2": total_sq ** 0.5,
            "abs_mean": abs_mean,
            "abs_max": total_abs_max,
            "zero_frac": total_zero / total_numel,
            "nonfinite_frac": total_nonfinite / total_numel,
            "numel": total_numel,
            "finite_numel": finite_numel,
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _select_stages(self, stage: Optional[str]):
        if stage is None:
            return list(self._stages.values())
        entry = self._stages.get(stage)
        if entry is None:
            raise KeyError(f"Unknown diagnostic stage: {stage}")
        return [entry]

    def _should_collect(self, enabled: bool, every: int) -> bool:
        if not enabled:
            return False
        if every <= 1:
            return True
        step = self._context.step
        return True if step is None else step % every == 0

    def _merge_tags(self, extra: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        tags = dict(self._context.tags)
        if extra:
            tags.update(extra)
        return tags

    def _refresh_stage_hooks(self, stage: str) -> None:
        handle = self._forward_handles.pop(stage, None)
        if handle is not None:
            handle.remove()

        handle = self._backward_handles.pop(stage, None)
        if handle is not None:
            handle.remove()

        entry = self._stages[stage]
        if entry.config.enabled:
            self._attach_stage_hooks(entry)
